[package]
name = "paperboids"
version = "0.1.0"
authors = ["quote <quote@dust.io>"]

[dependencies]
cgmath = "*"
# locked due to bug with dwm and glfw
glfw-sys = "=3.1.3"
glfw = "*"
time = "*"
gl = "*"
image = "*"
rand = "*"
tobj = "*"
